language: generic
dist: bionic


env:
  matrix:
    - PROVIDER=libvirt
    - PROVIDER=virtualbox

install:
  # - sudo apt-get install -y -q qemu vagrant virtualbox
  # - sudo apt-get install -y -q qemu vagrant
  # https://unix.stackexchange.com/questions/159094/how-to-install-a-deb-file-by-dpkg-i-or-by-apt
  - curl -sfLO https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_x86_64.deb
  - sudo apt-get install -y -q ./vagrant_2.2.6_x86_64.deb
  # https://github.com/vagrant-libvirt/vagrant-libvirt#installation
  # - sudo apt-get build-dep vagrant ruby-libvirt
  - sudo apt-get install -y -q ruby-libvirt qemu libvirt-bin ebtables dnsmasq-base libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev
  - if [ "$PROVIDER" = libvirt ]; then sudo vagrant plugin install vagrant-libvirt; fi
  - if [ "$PROVIDER" = virtualbox ]; then sudo apt-get install -y -q virtualbox; fi

script:
  - if [ "$PROVIDER" = virtualbox ]; then sudo VBoxManage --version; fi
  - sudo vagrant up --provider=$PROVIDER
